# Generated by Django 4.0.3 on 2022-04-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
