# Generated by Django 4.0.3 on 2022-04-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_stakeholder_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='pending',
        ),
        migrations.AddField(
            model_name='vendor',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
